<?php
/**
 *  @var \AHT\Blog\Block\CusIndex $block
 */
// echo $block->getBlogInfo();
	echo ("hello");
?> 
<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    	<a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="btn btn-primary btn-xs pull-right">Create New Post</a>
	  	<tr>
		    <th>Id</th>
		    <th>Name</th>
			<th width =" 20%" >Password</th>
		    <th ><span class="dashicons dashicons-email">Email</span></th>
		    <th colspan="3"> Action </th>
		    
	    </tr>
    </thead>
    <?php
	$customers = $block->getCustomers();
	
    foreach ($customers as $c) {
		
    	echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
    	echo "<td>".$c->getId()."</td>";
    	echo "<td>".$c->getName()."</td>";
		echo "<td>".$c->getPasswordHash()."</td>";
		echo "<td>".$c->getEmail()."</td>";
		// echo"<td><select onChange='window.document.location.href=this.options[this.selectedIndex].value;'>
  		// 			<option >Edit</option>
  		// 			<option ></option>
  		// 			<option ></option>
		// 		</select>
		// 	</td>";
		echo "<td><a href='".$block->getBaseUrl()."blog/index/cusedit?cus_id=".$c->getId()."'>Edit</a></td>";
		echo "<td><a href='".$block->getBaseUrl()."blog/index/cusdelete?cus_id=".$c->getId()."'>Delete!!!</a></td>";
		echo "<td><a href='".$block->getBaseUrl()."blog/index/cuschange?cus_id=".$c->getId()."'>Change Password</a></td>";
    	echo "</tr>";
    }
    ?>
</table>
