<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \KienAHT\Newp\Block\Product\Widget\NewProductList
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle();
    $items = $block->getProductCollection()->getItems();


    // foreach ($items as $product) {
    //     echo ($product->getId() . " ");
    // }
    // $listss = $block->getpro();
    // echo (" <br>  ");
    // foreach ($listss as $key => $product) {
    //     echo ($product->getId() . " ");
    // }
    $k = 0;
    $per = $block->getPageSize();
    $page = $block->getCurrentPage();
    $count = $block->getProductsCount();
    $eachpage = $block->getProductsPerPage();
    if ($count % $eachpage == 0) {
        $numpage = $count / $eachpage;
    } else {
        $numpage = round($count / $eachpage)+ 1;
    }
    // echo ("<br>" . $per . ": pagersize | " . $page . ":currentpage | " . $count . ": number | " . $eachpage . ": newproduct/page |" . $numpage . ": numberpage");
    // echo ("<br>".$items[0]->getId());

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<style>
    .prev:hover, .next:hover {
        background-color: rgba(0,0,0,0.8);
    }
    .prev, .next {
        cursor: pointer;
        position: absolute;
        top: 50%;
        width: auto;
        padding: 16px;
        margin-top: -22px;
        color: red;
        font-weight: bold;
        font-size: 18px;
        transition: 0.6s ease;
        border-radius: 0 3px 3px 0;
        user-select: none;
    }

    .next {
        right: 0;
        border-radius: 3px 0 0 3px;
    }
    * {
        box-sizing: border-box;
    }
    .kien-block{
        position: relative;
        z-index: 98;
    }
    body {
        font-family: Verdana, sans-serif;
    }

    .mySlides {
        display: none;
    }

    img {
        vertical-align: middle;
    }

    .block-content .slideshow-container {
        max-width: 100%;
        position: relative;
        margin: auto;
    }

    
    .ol{
        text-align: center;
    }
    

    .dot {
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
        z-index: 99;
    }

    .active {
        background-color: #717171;
    }

    /* Fading animation */
    .fade {
        -webkit-animation-name: fade;
        -webkit-animation-duration: 1.5s;
        animation-name: fade;
        animation-duration: 1.5s;
    }

    @-webkit-keyframes fade {
        from {
            opacity: .4
        }

        to {
            opacity: 1
        }
    }

    @keyframes fade {
        from {
            opacity: .4
        }

        to {
            opacity: 1
        }
    }

    /* On smaller screens, decrease text size */
    @media only screen and (max-width: 300px) {
        .text {
            font-size: 11px
        }
    }
</style>

<?php if ($exist) : ?>
<div class=" block widget block-new-products <?= $mode ?>">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $title ?></strong>
    </div>
    <div class="block-content kien-block">
        <div class="slideshow-container products-<?= $mode ?> <?= $mode ?>">
            <?php for ($i = 0; $i < $numpage; $i++) : ?>
            <div class="mySlides fade">
                <?php $j = $eachpage * $i; $k=0; echo (($i+1)."/".$numpage);  ?>
                <ol class="ol product-items <?=   $type ?>">
                    <?php foreach ($items as $key => $_item) : ?>
                        <?php if ($k == $j) : ?>
                            <?php
                            if ($j == $eachpage * ($i + 1)) {
                                    break;
                                }
                                $j++;
                            ?>
                        <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?=   $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?=   $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?=   $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?=   __('Add to Cart') ?>">
                                                            <span><?=   __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?=   $postData ?>'
                                                                type="button" title="<?=   __('Add to Cart') ?>">
                                                            <span><?=   __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?=   __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?=   __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?=   $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?=   __('Add to Wish List') ?>">
                                                        <span><?=   __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?=   $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?=   __('Add to Compare') ?>">
                                                        <span><?=   __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                     </li>
                        <?php endif ?>
                        <?php $k++; ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php endfor ?>
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>

        <div style="text-align:center">
            <?php for($i=0 ; $i<$numpage ; $i++):?>
                <span class="dot"></span>
            <?php endfor ?>
            
        </div>
    </div>
</div>
</div>


<?php endif; ?>

<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) {
            slideIndex = 1
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
        setTimeout(showSlides, 7000); 
    }
    showSlidesz(slideIndexz);

    function plusSlides(n) {
      showSlidesz(slideIndex += n);
    }

    function currentSlide(n) {
      showSlidesz(slideIndex = n);
    }

    function showSlidesz(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) { slideIndex = 1 }
      if (n < 1) { slideIndex = slides.length }
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active";
    }
</script>